name: CI 
on:
  pull_request:
    branches: [ main ]
    
env:
  output-dir: output
    
jobs:
  # This workflow contains a single job called "build"
  test:
    strategy:
      matrix:
        go-version: [1.16.5]
    runs-on: [ self-hosted, terraform ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: proxy
        uses: pri-actions/setup-proxy@v0.0.2

      - name: import secrets
        id: secrets
        uses: actions/vault-action@v2.1.2
        with:
          url: https://vaultsb.pfsfhq.com
          token: ${{ secrets.vaulttoken }}
          tlsskipverify: true
          secrets: |
            secret/data/prow github_token | github_token ;
            secret/data/prow minio_username | AWS_ACCESS_KEY_ID ;
            secret/data/prow minio_password | AWS_SECRET_ACCESS_KEY ;
      
      - name: setup-tf
        uses: pri-actions/setup-terraform@v2.0.2

      - name: Test
        run: |
          echo "PATH=$PATH:/usr/local/go/bin" >> $GITHUB_ENV
          make test/go
        env:
          TF_VAR_vault_token: ${{ secrets.VAULTTOKEN }}

